### PR TITLE
Allow direct uploads to AWS S3 from the browser

### PR DESCRIPTION
**Pull request by LeandroSNunes**
### Description
The front-ends need to upload directly to S3 via a pre-signed URL and this PR enable this feature

The steps to get of the AWS Credential is
1. Try to get the "Authorization" header
2. Try to get the "X-Amz-Credential" query string

I directly added the "Access-Control-Allow-Origin" header with the value "*" but I accept suggestions. :-/

### CODE REVIEW

**Review by andreleoni — APPROVED** [review]

**Comment by andreleoni** [comment]
@mhmoudgmal should you help us with feedback about these changes please? :pray:

**Review by andreleoni — APPROVED** [review]

**Comment by LeandroSNunes** [comment]
@mhmoudgmal has something that I should fixer?

**Comment by mhmoudgmal** [comment]
@LeandroSNunes Apologies for the late response, have been busy recently. 

I wanted to let you know that I got notified recently in localstack reop here https://github.com/localstack/localstack/issues/151  that they have supported a single endpoint for localstack services (is called Edge endpoint). 

So I am already stopping maintaining this repo (will update the  README shortly). From the feature implementation, I think they have a similar solution to what has been done in this repo, so I think it makes sense to start experimenting and relying on localstack itself instead of a proxy solution unless you have a good reason to use this repo, then I can recommend doing so in a fork since I am not maintaining the repo anymore.

Thank you! : )

**Comment by LeandroSNunes** [comment]
Ok @mhmoudgmal, thanks for the response.

**Pull request closed without merging**
